version: '3.8'

services:
  web-api:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: stss-api
    ports:
      - "5000:5000"
    volumes:
      - report_data:/app

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: stss-front
    ports:
      - "5173:80"
    depends_on:
      - web-api

volumes:
  report_data: